Update fd-cmd.md
johngrib/johngrib.github.io pull request #96
Opened 2020-01-30 13:12 UTC by jellygit

rust fd-find 명령을 잘 쓰고 있어서 설명을 좀 추가했습니다.

1. 공식홈페이지 링크 추가
1. 한글 사용예 페이지(zetawiki) 링크 추가
1. 예제 추가

2020-01-31 04:42 UTC, johngrib requested changes
멋진 PR에 감사드립니다.
몇 가지 변경 사항만 적용해 주시면 좋을 것 같습니다.

2020-01-31 04:42 UTC, johngrib commented on _wiki/fd-cmd.md
> +ㄴ ---
오타인 것 같아요. `ㄴ` 문자 삭제를 부탁드립니다.
```suggestion
---
```

2020-01-31 04:42 UTC, johngrib commented on _wiki/fd-cmd.md
> +* 공식홈페이지 https://github.com/sharkdp/fd/blob/master/README.md
주소 링크는 문서 하단에 `## Links` 문단을 추가하고 작성해주세요. 만약 번거로우시다면 이야기해주세요. 제가 하면 됩니다.

2020-01-31 04:42 UTC, johngrib commented on _wiki/fd-cmd.md
> +* 사용예(한글페이지) https://zetawiki.com/wiki/Fd-find
주소 링크는 문서 하단에 `## Links` 문단을 추가하고 작성해주세요. 만약 번거로우시다면 이야기해주세요. 제가 하면 됩니다.

2020-01-31 04:42 UTC, johngrib commented on _wiki/fd-cmd.md
> +## fd-find
`fd-find`는 `fd`의 대체이므로 `## Examples` 아래쪽으로 가는 것이 좋을 것 같습니다.

2020-02-01 17:44 UTC, jellygit commented on _wiki/fd-cmd.md
> +## fd-find
fd 로만 표기하는게 맞겠네요.
Debian, Fedora, Ubuntu 정도만 fd-find 라고 표현하는 것을 오인해서 fd-find 가 공식 명칭인줄 알았습니다. 제작자 홈페이지도 fd 라고만 적어놓았습니다.

2020-02-01 23:43 UTC, johngrib requested changes
작업에 감사드립니다. 아래와 같이 추가 변경 사항을 요청합니다.
리뷰와 수정 과정이 번거롭고 힘드시겠지만 모처럼 들어온 좋은 PR이라 클로즈 없이 가면 좋겠습니다.

이번 리뷰는 크게 다음과 같은 요청을 갖습니다.

* 숫자 목록보다 일반 목록을 사용해 주세요. 숫자 목록은 ordered set 의 의미를 살리고 싶은 경우에만 사용해 주세요.
* 몇몇 표현의 수정을 부탁드립니다.
* 같은 의미를 갖는 더 단순한 정규식으로 수정해 주세요.
* 사실관계에 대해 원본 문서의 링크를 적절한 단어에 연결해주세요.
* 이 파일은 `fd`의 예제를 incremental하게 증가시키는 문서이므로, 타 예제 사이트를 소개하는 것은 적절하지 않습니다.

한편, 1ffecb2 와 23ec7e0 두 커밋의 타이틀이 `1. 외부 하이퍼링크 단락 추가`와 같이 `1.` 으로 시작하고 있습니다. 커밋 메시지 타이틀의 수정을 권유드립니다.

만약 git에 익숙하지 않아 타이틀 수정에 어려움을 느끼신다면 말씀해주세요. [이 PR](https://github.com/johngrib/johngrib.github.io/pull/96 )을 일단 머지시킨 다음 제가 히스토리를 수동으로 리베이스하여 고치겠습니다.

2020-02-01 23:43 UTC, johngrib commented on _wiki/fd-cmd.md
> + # 2019년 하반기에 변경된 일반 파일 찾기
다음과 같이 표현 변경을 권합니다.
```suggestion
 # 2019년 하반기에 변경된 파일을 찾는다
```

2020-02-01 23:43 UTC, johngrib commented on _wiki/fd-cmd.md
> + fd -t f '.*\.py$|.*\.pl$'
더 심플한 정규식을 제안합니다.
```suggestion
 fd -t f '\.(py|pl)$'
```

2020-02-01 23:43 UTC, johngrib commented on _wiki/fd-cmd.md
> +1. Rust 로 작성된 xNIX find 유틸리티
숫자 리스트는 적절하지 않습니다. 리스트로 선언해 주세요. 
```suggestion
* Rust 로 작성된 xNIX find 유틸리티
```

2020-02-01 23:43 UTC, johngrib commented on _wiki/fd-cmd.md
> +1. Rust 로 작성된 xNIX find 유틸리티
다음과 같은 표현을 제안합니다.
```suggestion
* Rust 로 작성된 find 명령의 대안
```

2020-02-01 23:43 UTC, johngrib commented on _wiki/fd-cmd.md
> +1. 멀티스레드로 검색하므로 find보다 더 빠른 검색 결과(공식 홈페이지 Benchmark 항목 참조).
다음과 같은 표현을 제안합니다.
```suggestion
* [벤치마크 결과](https://github.com/sharkdp/fd#benchmark )를 보면 `find`보다 빠르다.
```

2020-02-01 23:43 UTC, johngrib commented on _wiki/fd-cmd.md
> +1. find 명령 옵션 및 사용 방법에 차이점에 있어 완전한 대체는 되지 않으나(80% 정도라고) 훨씬 빠르게 결과 얻을 수 있다.
다음과 같은 표현을 제안합니다.
```suggestion
* `find`를 완전히 대체하지는 못한다. [유즈 케이스의 80% 정도 커버 가능](https://github.com/sharkdp/fd#fd ). 
```

2020-02-01 23:43 UTC, johngrib commented on _wiki/fd-cmd.md
> +1. [fd 공식홈페이지](https://github.com/sharkdp/fd/)
```suggestion
* [sharkdp/fd](https://github.com/sharkdp/fd/ )
```

2020-02-01 23:43 UTC, johngrib commented on _wiki/fd-cmd.md
> +1. [사용예-zetawiki](https://zetawiki.com/wiki/Fd-find)
불필요한 라인입니다.

2020-02-02 07:08 UTC, johngrib approved these changes
고생하셨습니다. 감사합니다.

2020-02-02 07:10 UTC, merged